### ISSUE TITLE
Capability to hide items in slash menu

### ISSUE THREAD

**Issue by XeroChina** [zxkmm/siyuan_rmv_btn#1]
编辑器里按“/"，会出现快捷功能菜单，能否隐藏这个菜单中的内容呢？我想把”AI Chat"去除掉。国内根本用不了Open AI。
![image](https://github.com/zxkmm/siyuan_rmv_btn/assets/140034797/2676cd15-354b-49a9-8c8b-b2e41c586778)

**Comment by zxkmm** [comment]
谢谢建议，这个菜单是编辑器的内容块里面调用的，我暂时不知道如果也是用现阶段的DOM监听 + style改none的方式会对性能有多大的影响。因为理论上如果文本又长内容块又多的话，遍历的时间复杂度会变成指数函数。   
我没有读过思源的编辑器前端实现，不太好下定论。  
等我先实现一下，然后我先自己观察一下，如果对性能影响不大的话，我就把这个功能集成到新版本中。   
如果比较急的话也可以在上架之前关注一下新的测试branch.

**Comment by Xiaobaishushu25** [comment]
你好，请问这个功能现在处于什么状态？

**Comment by zxkmm** [comment]
我在想比监听器优雅的方案，因为这个功能的性能折扣暂时没办法接受。（我是完美主义者）

**Comment by Xiaobaishushu25** [comment]
> 我在想比监听器优雅的方案，因为这个功能的性能折扣暂时没办法接受。（我是完美主义者）

了解，支持，感谢😀

**Comment by jiusun** [comment]
可以考虑在 `设置-外观-代码片段` 中添加一个自定义的CSS样式来屏蔽按 `/` 里不想要的菜单

```css
/** 编辑器 / 命令中的 AI Chat */
[data-value="%E2%80%8B5"]
{
  display: none !important;
}
```
